<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  
  <ItemGroup Label="Apis">
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.*" />
    
    <PackageVersion Include="Scalar.AspNetCore" Version="2.*" />
    <PackageVersion Include="Scalar.AspNetCore.Microsoft" Version="2.*" />
  </ItemGroup>
  
  <ItemGroup Label="EfCore">
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.*" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.*" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.*" />
    
  </ItemGroup>

  <ItemGroup Label="Tests">
    <PackageVersion Include="xunit.v3.mtp-v2" Version="3.*" />
  </ItemGroup>

</Project>
