<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <None Include="ApiEndpointRouteBuilderExtensions.cs" />

    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Scalar.AspNetCore.Microsoft" />
  </ItemGroup>

</Project>
