<Project>
  <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->

  <ItemGroup>
    <ProjectReference Include="..\..\src\Company.Common.Api\Company.Common.Api.csproj" />
    <ProjectReference Include="..\..\src\Company.Common.EfCore\Company.Common.EfCore.csproj" />
  </ItemGroup>
  
  <Import Project="../Directory.Build.targets" />

</Project>
