<Project>
  <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Scalar.AspNetCore.Microsoft" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <Import Project="../Directory.Build.targets" />

</Project>
